name: Android Build

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Prepare Keystore
        id: keystore
        run: |
          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/release.keystore
            echo "ks_path=${{ github.workspace }}/release.keystore" >> $GITHUB_OUTPUT
            echo "ks_pass=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_OUTPUT
            echo "ks_alias=${{ secrets.KEY_ALIAS }}" >> $GITHUB_OUTPUT
            echo "ks_key_pass=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_OUTPUT
          else
            echo "No signing secrets found, generating temporary keystore..."
            keytool -genkeypair -v -keystore ${{ github.workspace }}/release.keystore               -alias temp -keyalg RSA -keysize 2048 -validity 10000               -storepass temp123 -keypass temp123               -dname "CN=KunBox, OU=Devl, O=KunBox, L=SH, ST=SH, C=CN"
            echo "ks_path=${{ github.workspace }}/release.keystore" >> $GITHUB_OUTPUT
            echo "ks_pass=temp123" >> $GITHUB_OUTPUT
            echo "ks_alias=temp" >> $GITHUB_OUTPUT
            echo "ks_key_pass=temp123" >> $GITHUB_OUTPUT
          fi

      - name: Normalize and grant execute permission for gradlew
        run: |
          sed -i 's/\r$//' ./gradlew
          chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          mkdir -p dist
          ./gradlew assembleRelease -PabiOnly=arm64-v8a
          find app/build/outputs/apk/release -type f -name "*.apk" -exec cp {} dist/ \;
          rm -f app/build/outputs/apk/release/*.apk
          ./gradlew assembleRelease -PabiOnly=armeabi-v7a
          find app/build/outputs/apk/release -type f -name "*.apk" -exec cp {} dist/ \;
        env:
          KEYSTORE_PATH: ${{ steps.keystore.outputs.ks_path }}
          KEYSTORE_PASSWORD: ${{ steps.keystore.outputs.ks_pass }}
          KEY_ALIAS: ${{ steps.keystore.outputs.ks_alias }}
          KEY_PASSWORD: ${{ steps.keystore.outputs.ks_key_pass }}
          VERSION_NAME: ${{ github.ref_name }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kunbox-apk
          path: dist/*.apk
